//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fiinance.dataaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string symbol { get; set; }
        public string company_name { get; set; }
        public string sector { get; set; }
        public string sub_industry { get; set; }
    }
}
